"""empty message

Revision ID: c93e3998f529
Revises: e9b6b309a40c
Create Date: 2025-08-05 21:10:55.958982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93e3998f529'
down_revision = 'e9b6b309a40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsprofileCompletd', sa.Boolean(), nullable=True))
        batch_op.drop_column('profileCompletd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profileCompletd', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('IsprofileCompletd')

    # ### end Alembic commands ###
